
- name: Create project dirs
  file:
    path: "{{ project_path }}/releases"
    state: directory

- name: Clone repo
  git:
    repo: "{{ git_repo }}"
    dest: "{{ project_path }}/releases/current"

- name: Start app
  shell: docker-compose up -d
  args:
    chdir: "{{ project_path }}/releases/current/docker"
